services:
  orthos2:
    build:
      context: .
      dockerfile: docker/develop-tw.dockerfile
    hostname: orthos2.orthos2.test
    env_file:
      - "orthos2.env"
      - "db.env"
    cap_add:
      - NET_RAW
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
  orthos2_taskmanager:
    build:
      context: .
      dockerfile: docker/develop-tw.dockerfile
    environment:
      ORTHOS2_MODE: "taskmanager"
    env_file:
      - "db.env"
    cap_add:
      - NET_RAW
    volumes:
      - ./:/code
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    restart: always
    hostname: database.orthos2.test
    environment:
      POSTGRES_USER: orthos
      POSTGRES_PASSWORD: orthos2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_USER} -U $${POSTGRES_USER}" ]
      interval: 1s
      timeout: 5s
      retries: 10
  cobbler:
    hostname: cobbler.orthos2.test
    build:
      context: .
      dockerfile: docker/cobbler.dockerfile
    ports:
      # - "22:22"
      - "80:80"
      - "443:443"
  serial_console:
    hostname: sconsole.orthos2.test
    build:
      context: .
      dockerfile: docker/serial-console.dockerfile
    #ports:
    #  - 22:22
  machine_bmc:
    hostname: bmc.orthos2.test
    build:
      context: docker
      dockerfile: bmc.dockerfile
    ports:
      - "9001:9001"
