[tool.isort]
profile = "black"
known_cobbler="orthos2"
known_tests="tests"
sections="FUTURE,STDLIB,FIRSTPARTY,THIRDPARTY,LOCALFOLDER,COBBLER,TESTS"

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "strict"
useLibraryCodeForTypes = true
exclude = ["build", "venv", ".venv", "orthos2/data/migrations"]
