name: Django CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip
    - run: |
        sudo apt-get install libldap2-dev libsasl2-dev
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Install Dependencies
      run: |
        sudo apt-get install python3-setuptools
    - name: Create Logfiles
      run: |
        sudo mkdir -p /var/log/orthos2
        sudo touch /var/log/orthos2/default.log
        sudo chmod o+w /var/log/orthos2/default.log
        sudo groupadd -r orthos
        sudo useradd -r -g orthos -d /var/lib/orthos2 -s /bin/bash -c "orthos account" orthos
    - name: Install orthos2
      run: |
        sudo python3 setup.py install
    - name: Migrate database
      run: |
        cd orthos2
        sudo -u orthos bin/manage.py migrate
    - name: Run Tests
      run: |
        sudo -u orthos python3 bin/manage.py loaddata data/fixtures/*.json
        sudo -u orthos python3 bin/manage.py loaddata taskmanager/fixtures/*.json
        sudo -u orthos python3 bin/manage.py test
