name: Coding Style

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  isort:
    name: isort
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.6
      - uses: isort/isort-action@master
        with:
          requirementsFiles: "pyproject.toml"
  pylint:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=.pylintrc --fail-under=10 `find -regextype egrep -regex '(.*.py)$'`
  pycodingstyle:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pycodestyle
    - name: Analysing the code with pycodestyle
      run: |
        pycodestyle .
  django-admin:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt-get install python3-setuptools libldap2-dev libsasl2-dev 
          python -m pip install --upgrade pip
          python -m pip install -r requirements-devel.txt
      - name: Analysing the code with "django-admin check"
        run: |
          python manage.py check
